from manager.models_type import DBVarchar, DBInt

from manager.models_type import table_keys

@table_keys('AuthorId')
class Author:
    AuthorId = DBInt(autogenerated=True)
    FirstName = DBVarchar(max_len=50, not_null=True)
    LastName = DBVarchar(max_len=50)
