from manager.models_type import DBInt, DBVarchar
from manager.models_type import DBMoney, DBDate, DBForeignKey
from manager.models_type import table_keys

from models.publisher import Publisher
from models.author import Author

@table_keys('BookId')
class Book:
    BookId = DBInt(autogenerated=True)
    Title = DBVarchar(max_len=250, not_null=True)
    CoverImage = DBVarchar(max_len=500)
    PubishDate = DBDate()
    Price = DBMoney()
    PublisherId = DBForeignKey(Publisher, "PublisherId")
    AuthorId = DBForeignKey(Author, "AuthorId")
