from manager.models_type import DBInt, DBVarchar
from manager.models_type import table_keys

@table_keys('PublisherId')
class Publisher:
    PublisherId = DBInt(autogenerated=True)
    Country = DBVarchar(max_len=60)
    Name = DBVarchar()
