from manager.models_type import DBForeignKey, DBDate, DBInt
from manager.models_type import table_keys

from models.user import User
from models.book import Book

@table_keys('PurchaseId', 'UserId', 'BookId')
class Purchases:
    PurchaseId = DBInt(autogenerated=True)
    UserId  = DBForeignKey(User, "UserId")
    BookId    = DBForeignKey(Book, "BookId")
    PurchaseDate = DBDate()
