from manager.models_type import DBInt, DBVarchar
from manager.models_type import table_keys

@table_keys('UserId')
class User:
    UserId = DBInt(autogenerated=True)
    Email = DBVarchar(max_len=100, not_null=True)
    Password = DBVarchar(max_len=500, not_null=True)
    Role = DBVarchar(max_len=50, not_null=True)
